// Auto-generated optimized Heroicons exports
// This file exports only the icons used in the application

// Outline icons
export {
    AcademicCapIcon,
    AdjustmentsHorizontalIcon,
    ArrowDownTrayIcon,
    ArrowPathIcon,
    ArrowPathRoundedSquareIcon,
    ArrowRightIcon,
    ArrowTrendingDownIcon,
    ArrowTrendingUpIcon,
    ArrowUturnLeftIcon,
    BeakerIcon,
    BellIcon,
    BoltIcon,
    BookOpenIcon,
    BriefcaseIcon,
    BugAntIcon,
    BuildingOfficeIcon,
    CalendarIcon,
    ChartBarIcon,
    ChatBubbleLeftIcon,
    ChatBubbleLeftRightIcon,
    CheckCircleIcon,
    CheckIcon,
    ChevronDownIcon,
    ChevronLeftIcon,
    ChevronRightIcon,
    ChevronUpIcon,
    ClipboardIcon,
    ClockIcon,
    CodeBracketIcon,
    Cog6ToothIcon,
    CogIcon,
    ComputerDesktopIcon,
    CpuChipIcon,
    CreditCardIcon,
    CubeIcon,
    CurrencyDollarIcon,
    DevicePhoneMobileIcon,
    DocumentArrowDownIcon,
    DocumentDuplicateIcon,
    DocumentPlusIcon,
    DocumentTextIcon,
    EllipsisVerticalIcon,
    EnvelopeIcon,
    ExclamationTriangleIcon,
    EyeIcon,
    EyeSlashIcon,
    FireIcon,
    FunnelIcon,
    GlobeAltIcon,
    HandThumbDownIcon,
    HandThumbUpIcon,
    HeartIcon,
    HeartIcon as HeartIconSolid,
    InformationCircleIcon,
    KeyIcon,
    LightBulbIcon,
    LinkIcon,
    LockClosedIcon,
    MagnifyingGlassIcon,
    MegaphoneIcon,
    PaperAirplaneIcon,
    PauseIcon,
    PencilIcon,
    PlayCircleIcon,
    PlayIcon,
    PlusIcon,
    QuestionMarkCircleIcon,
    ArrowUturnLeftIcon as ReplyIcon,
    RocketLaunchIcon,
    ScaleIcon,
    ServerIcon,
    ShareIcon,
    ShieldCheckIcon,
    ShieldExclamationIcon,
    SignalIcon,
    SparklesIcon,
    StarIcon,
    StopIcon,
    TagIcon,
    TrashIcon,
    TrophyIcon,
    UserGroupIcon,
    UserIcon,
    UserPlusIcon,
    VideoCameraIcon,
    WrenchScrewdriverIcon,
    XCircleIcon,
    XMarkIcon
} from '@heroicons/react/24/outline';

// Solid icons (add as needed)
export { StarIcon as StarIconSolid } from '@heroicons/react/24/solid';
